/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class Weather {
  Weather._();

  static const _kFontFam = 'Weather';

  static const IconData fog = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData rain = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData snow_heavy =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData clouds_flash_alt =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData wind = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData temperature =
      const IconData(0xe809, fontFamily: _kFontFam);
}
